name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Lint with Ruff
        run: ruff check --output-format=github .
        continue-on-error: true

  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'python'
          build-mode: 'none'
          queries: security-and-quality
          upload: 'never'

      - name: Perform CodeQL Analysis
        id: codeql_analyze
        uses: github/codeql-action/analyze@v3
        with:
          output: ./codeql-results

      # (Optional) Upload SARIF file as an artifact
      - name: Upload SARIF file
        uses: actions/upload-artifact@v3
        with:
          name: codeql-sarif
          path: ./codeql-results/**/*.sarif

      # Example step to process the SARIF file
      # This is a placeholder for your actual processing script
      - name: Process SARIF Output
        run: |
          echo "Process SARIF files here"
          # Example: ls -l ./codeql-results
          # Replace the above with your actual processing commands